version: 2
updates:
- package-ecosystem: elm
  directory: "/assets/elm"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 2
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 2
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 2
  ignore:
  - dependency-name: terser-webpack-plugin
    versions:
    - 5.1.1
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
