version: 2
updates:
  - package-ecosystem: elm
    directory: '/assets/elm'
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: mix
    directory: '/'
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: npm
    directory: '/assets'
    schedule:
      interval: weekly
      day: saturday

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
