version: 2
updates:
  - package-ecosystem: mix
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
    ignore:
      # `dependency-name` is required.
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: npm
    directory: '/assets'
    schedule:
      interval: weekly
      day: saturday
    ignore:
      # `dependency-name` is required.
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      tailwind:
        patterns:
          - '@tailwindcss/*'
          - 'tailwindcss'
        update-types:
          - 'minor'
          - 'patch'
      misc:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
