matrix:
  include:
    - language: elixir
      elixir: '1.8.2'
      otp_release: '20.0'

      cache:
        directories:
          - _build
          - deps

      services:
        - postgresql

      addons:
        postgresql: '9.6'

      before_script:
        - cp config/test.travis.exs config/test.exs
        - psql -c 'create database travis_ci_test;' -U postgres

    - language: node_js
      node_js: node

      cache:
        directories:
          - assets/node_modules
          - assets/elm/elm-stuff

      before_install:
        - cd assets

      install:
        - npm install

      script:
        - npm run deploy
        - cd elm && npx elm-format --validate app tests
        - npm test
