matrix:
  include:
    - language: elixir
      elixir: '1.8.2'
      otp_release: '20.0'

      cache:
        directories:
          - _build
          - deps

      services:
        - postgresql

      addons:
        postgresql: '9.6'

      before_script:
        - cp config/test.travis.exs config/test.exs
        - psql -c 'create database travis_ci_test;' -U postgres

      script:
        - mix format --check-formatted
        - mix test

    - language: node_js
      node_js: 10

      cache:
        directories:
          - assets/node_modules
          - assets/elm/elm-stuff

      before_install:
        - cd assets

      install:
        - npm install

      script:
        - npm run deploy
        - npx elm-format --elm-version=0.19 --validate elm
        - npm test
        - npx prettier --check "js/**/*.js" "*.js"
