language: elixir
elixir: '1.6.4'
otp_release: '20.0'

cache:
  directories:
    - _build
    - deps

services:
  - postgresql

addons:
  postgresql: '9.6'

before_script:
  - cp config/test.travis.exs config/test.exs
  - psql -c 'create database travis_ci_test;' -U postgres
